[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "src"
version = "0.0.1"
dependencies = [
    "package0==1.0.0"
]

[project.optional.dependencies]
optional1 = [
    "package1==1.0.0"
]

optional2 = [
    "package2==1.0.0"
]